### ISSUE TITLE
Please clarify inline comment in new "results" classes body in common.cf - a promise can be both kept and failed at the same time

### ISSUE THREAD

**Issue by atsaloli** [cfengine/masterfiles#688]
Hello,
Thank you for adding the new "results" classes body.

It's great to have this more concise classes body.

Could you please clarify the inlie comment "_ok is not defined by this bundle, as a promsie could be both kept and failed at the same time" -- how can a promise be both KEPT and FAILED at the same time?

The only documentation I could find about promise outcomes is in reference/enterprise-api-ref/sql-schema.markdown in the documentation project:

* **PromiseOutcome** *(`KEPT`/`NOTKEPT`/`REPAIRED`)*
    Promise execution result.
    * `KEPT` - System has been found in the state as desired by the promise. CFEngine did not have to do any action to correct the state.
    * `REPAIRED` - State of the system differed from the desired state. CFEngine took successful action to correct it according to promise specification.
    * `NOTKEPT` - CFEngine has failed to converge the system according to the promise specification.

Is it me, or are promise outcomes missing from Language Concepts?

**Comment by mikeweilgart** [comment]
Addendum: We found this while looking at 3.7.3 ([here are the relevant lines](https://github.com/cfengine/masterfiles/blob/3.7.3/lib/3.7/common.cf#L288-L289)), but I see that a similar statement [still exists in the master branch](https://github.com/cfengine/masterfiles/blob/206a8b2e6bf277c3df9b57bf5c535b0b6dba963a/lib/common.cf#L299-L300).

Perhaps this refers to a promise being both kept and failed *during separate passes*...?  (Not clear.)

**Comment by nickanderson** [comment]
Does this make more sense?

@@ -294,10 +294,15 @@ body classes results(scope, class_prefix)
 # `abc_reached` and `abc_repaired` will be set.
 #
 # This body is a simpler, more consistent version of the body
-# `scoped_classes_generic`, which see. The key difference is that
-# fewer classes are defined, and only for outcomes that we can know.
-# For example this body does not define "OK/not OK" outcome classes,
-# since a promise can be both kept and failed at the same time.
+# `scoped_classes_generic`, which see. The key difference is that fewer classes
+# are defined, and only for outcomes that we can know. For example, the
+# `scoped_classes_generic` body will define an `_ok` suffixed class if the
+# promise is seen to be kept or repaired. The class name itself can be
+# misleading as it is defined even if another part of the promise results in the
+# definition of `_not_kept` suffixed classes. Similarly the `if_ok` classes body
+# defines the class passed to the body if the promise results in a kept or
+# repaired outcome even if another part of the promise results in a not kept
+# outcome.
 #
 # It's important to understand that promises may do multiple things,
 # so a promise is not simply "OK" or "not OK." The best way to

**Comment by nickanderson** [comment]
Also please file issues in the official tracker. Issues here on github are supposed to be disabled (and will be in the future, thanks for reminding me).
